# -*- coding: utf-8 -*-
# file: fde.py

# This code is part of Poraquê.
# MIT License
#
# Copyright (c) 2026 Leandro Seixas Rocha <leandro.rocha@ilum.cnpem.br>

"""Frozen-Density Embedding (subsystem DFT).

This module implements the Wesolowski-Warshel frozen-density embedding scheme.
The supersystem density is partitioned into subsystem densities
``n_tot = sum_I n_I``; each subsystem is relaxed in the embedding potential
generated by the others, optionally cycling (freeze-and-thaw) until the total
density and energy are self-consistent.

Subsystems may be solved with either the orbital-free engine
(:class:`~poraque.engine.OFDFTEngine`) or the Kohn-Sham engine
(:class:`~poraque.engine.KSDFTEngine`), enabling OF-in-OF, KS-in-KS, and mixed
KS-in-OF / OF-in-KS embedding on a shared real-space grid.
"""

import numpy as np

from .core import Density, Result, SolverSettings
from .engine import KSDFTEngine, OFDFTEngine
from .functionals import External, Hartree, LDA, TFvW
from .potentials import build_external_potential


class Subsystem:
    """
    A single FDE subsystem.

    Parameters
    ----------
    system : System
        The subsystem nuclei and electron count.
    method : {"of", "ks"}, optional
        Solver used to relax this subsystem (default ``"of"``).
    kedf : Functional, optional
        Kinetic energy density functional used both as the OF intra-subsystem
        kinetic term and (engine-wide) for the nonadditive kinetic energy.
        Defaults to ``TFvW(lambda_vw=1.0)``.
    xc : Functional, optional
        Exchange-correlation functional (default :class:`~poraque.functionals.LDA`).
    name : str, optional
        Human-readable label.
    external_kind : str, optional
        External-potential model for this subsystem's nuclei.
    external_kwargs : dict, optional
        Extra arguments for the external-potential builder.
    """

    def __init__(self, system, method="of", kedf=None, xc=None, name="",
                 external_kind="soft", external_kwargs=None):
        self.system = system
        self.method = method
        self.kedf = kedf if kedf is not None else TFvW(lambda_vw=1.0)
        self.xc = xc if xc is not None else LDA()
        self.name = name or "subsystem"
        self.external_kind = external_kind
        self.external_kwargs = external_kwargs or {}
        self.density = None  # set during initialization on the shared grid


class FDEEngine:
    """
    Frozen-density embedding driver on a shared grid.

    Parameters
    ----------
    subsystems : list of Subsystem
        The partitioned subsystems.
    grid : Grid
        The shared real-space grid.
    backend : Backend
        Numerical backend.
    settings : SolverSettings, optional
        Outer freeze-and-thaw settings (``max_iter`` = number of cycles,
        ``tolerance`` = total-density residual threshold). Subsystem solves use
        their own inner settings.
    inner_settings : SolverSettings, optional
        Settings passed to each subsystem solve.
    kedf_nad : Functional, optional
        KEDF used for the nonadditive kinetic energy/potential. Defaults to the
        first subsystem's ``kedf``.
    xc_nad : Functional, optional
        XC functional for the nonadditive XC term. Defaults to the first
        subsystem's ``xc``.
    """

    def __init__(self, subsystems, grid, backend, settings=None,
                 inner_settings=None, kedf_nad=None, xc_nad=None):
        self.subsystems = subsystems
        self.grid = grid
        self.backend = backend
        self.settings = settings or SolverSettings(max_iter=10, tolerance=1e-5)
        self.inner_settings = inner_settings or SolverSettings(
            max_iter=60, tolerance=1e-6, mixing=0.1
        )
        self.kedf_nad = kedf_nad if kedf_nad is not None else subsystems[0].kedf
        self.xc_nad = xc_nad if xc_nad is not None else subsystems[0].xc

        # Per-subsystem external potential from its own nuclei.
        self._vext = [
            build_external_potential(grid, s.system, kind=s.external_kind,
                                     **s.external_kwargs)
            for s in subsystems
        ]
        self._vext_tot = np.sum(self._vext, axis=0)
        self._init_densities()

    def _init_densities(self):
        """Seed each subsystem with a normalized uniform density."""
        for s in self.subsystems:
            if s.density is None:
                n0 = s.system.electrons / self.grid.volume
                s.density = Density(self.grid, np.full(self.grid.shape, n0))
            s.density.normalize(s.system.electrons)

    def total_density(self):
        """Return the supersystem density ``n_tot = sum_I n_I``."""
        data = np.zeros(self.grid.shape)
        for s in self.subsystems:
            data += s.density.data
        return Density(self.grid, data)

    def embedding_potential(self, i, n_tot=None):
        """
        Build the embedding potential felt by subsystem ``i``.

        .. math::

            v^{I}_{emb} = v^{others}_{ext} + v_H[n_{others}]
                        + \\big(v_{xc}[n_{tot}] - v_{xc}[n_I]\\big)
                        + \\big(v_{Ts}[n_{tot}] - v_{Ts}[n_I]\\big)
        """
        s = self.subsystems[i]
        if n_tot is None:
            n_tot = self.total_density()
        n_i = s.density
        n_others_data = n_tot.data - n_i.data
        n_others = Density(self.grid, n_others_data)

        v_ext_others = self._vext_tot - self._vext[i]
        v_h_others = self.backend.poisson(n_others_data, self.grid)
        v_xc_nad = (self.xc_nad.potential(n_tot, s.system, self.grid, self.backend)
                    - self.xc_nad.potential(n_i, s.system, self.grid, self.backend))
        v_ts_nad = (self.kedf_nad.potential(n_tot, s.system, self.grid, self.backend)
                    - self.kedf_nad.potential(n_i, s.system, self.grid, self.backend))
        return v_ext_others + v_h_others + v_xc_nad + v_ts_nad

    def _solve_subsystem(self, i, v_emb):
        """Relax subsystem ``i`` in the (frozen) embedding potential."""
        s = self.subsystems[i]
        v_total_ext = self._vext[i] + v_emb

        if s.method == "of":
            functionals = [s.kedf, Hartree(), s.xc, External(v_total_ext)]
            engine = OFDFTEngine(s.system, self.grid, functionals,
                                 self.backend, self.inner_settings)
            result = engine.run(Density(self.grid, s.density.data.copy()))
        elif s.method == "ks":
            engine = KSDFTEngine(s.system, self.grid, v_total_ext, self.backend,
                                 self.inner_settings, xc=s.xc, hartree=True)
            result = engine.run(Density(self.grid, s.density.data.copy()))
        else:
            raise ValueError(f"Unknown subsystem method: {s.method!r}")

        s.density = result.density
        return result

    def total_energy(self):
        """
        Total embedded energy: subsystem intra-energies plus interaction terms.

        ``E = sum_I E_I[n_I] + E_es^{inter} + E_xc^{nad} + E_Ts^{nad}`` where the
        nuclear-nuclear interaction (a density-independent constant) is omitted.
        """
        n_tot = self.total_density()
        hartree = Hartree()

        e_intra = 0.0
        e_h_sum = 0.0
        e_xc_sum = 0.0
        e_ts_sum = 0.0
        e_en_sum = 0.0  # sum_I integral(n_I v_ext_I)

        for i, s in enumerate(self.subsystems):
            n_i = s.density
            t_i = s.kedf.energy(n_i, s.system, self.grid, self.backend)
            h_i = hartree.energy(n_i, s.system, self.grid, self.backend)
            xc_i = s.xc.energy(n_i, s.system, self.grid, self.backend)
            en_i = self.backend.integrate(self._vext[i] * n_i.data, self.grid)
            e_intra += t_i + h_i + xc_i + en_i
            e_h_sum += h_i
            e_xc_sum += xc_i
            e_ts_sum += t_i
            e_en_sum += en_i

        # Interaction (nonadditive) terms.
        e_h_tot = hartree.energy(n_tot, None, self.grid, self.backend)
        e_en_tot = self.backend.integrate(self._vext_tot * n_tot.data, self.grid)
        e_xc_tot = self.xc_nad.energy(n_tot, None, self.grid, self.backend)
        e_ts_tot = self.kedf_nad.energy(n_tot, None, self.grid, self.backend)

        e_es_inter = (e_h_tot - e_h_sum) + (e_en_tot - e_en_sum)
        e_xc_nad = e_xc_tot - e_xc_sum
        e_ts_nad = e_ts_tot - e_ts_sum

        e_total = e_intra + e_es_inter + e_xc_nad + e_ts_nad
        components = {
            "Intra": e_intra,
            "Electrostatic (inter)": e_es_inter,
            "XC (nonadditive)": e_xc_nad,
            "Kinetic (nonadditive)": e_ts_nad,
        }
        return e_total, components

    def freeze_and_thaw(self):
        """
        Run alternating subsystem relaxations until the total density converges.

        Returns
        -------
        Result
            Total embedded energy, total density, and convergence history.
        """
        history = {"energy": [], "density_residual": []}
        converged = False
        energy, components = self.total_energy()

        cycle = 0
        for cycle in range(self.settings.max_iter):
            prev_tot = self.total_density().data.copy()

            for i in range(len(self.subsystems)):
                v_emb = self.embedding_potential(i)
                self._solve_subsystem(i, v_emb)

            new_tot = self.total_density().data
            residual = (self.backend.norm(new_tot - prev_tot)
                        * np.sqrt(self.grid.volume_element))
            energy, components = self.total_energy()
            history["energy"].append(energy)
            history["density_residual"].append(residual)

            if residual < self.settings.tolerance:
                converged = True
                break

        return Result(
            energy=energy,
            components=components,
            density=self.total_density(),
            converged=converged,
            iterations=cycle + 1,
            history=history,
        )
