# -*- coding: utf-8 -*-
# file: test_guides.py

"""
The LaTeX guides must not carry a version of their own.

Both did, as literals on the title page, and both had drifted: the user guide
said 26.8.18 and the technical guide 26.6.4 while the package was on 26.8.27.
A version a reader cannot trust is worse than no version, and nothing in a
PDF build fails when it goes stale — so it needs a test.
"""

import os
import re

import pytest

ROOT = os.path.join(os.path.dirname(__file__), "..")
GUIDES = ("user_guide/poraque_user_guide",
          "technical_guide/poraque_technical_guide")


def _read(relative):
    with open(os.path.join(ROOT, relative)) as handle:
        return handle.read()


@pytest.mark.parametrize("guide", GUIDES)
class TestVersionIsNotHardCoded:
    def test_the_title_page_uses_the_macro(self, guide):
        source = _read(f"latex/{guide}.tex")
        assert r"\poraqueversion" in source

    def test_no_literal_version_survives(self, guide):
        """
        A bare ``Version 26.8.18`` on the title page is exactly the failure
        this replaced.
        """
        source = _read(f"latex/{guide}.tex")
        literals = re.findall(r"Version\s+\d+\.\d+\.\d+", source)
        assert not literals, f"hard-coded version(s): {literals}"

    def test_the_macro_has_a_fallback(self, guide):
        """
        The stamp is generated by the Makefile. Compiled directly with
        ``pdflatex``, the document must still build rather than die on an
        undefined control sequence.
        """
        source = _read(f"latex/{guide}.tex")
        assert r"\providecommand{\poraqueversion}" in source
        assert source.index(r"\IfFileExists{poraque_version.tex}") < \
            source.index(r"\providecommand{\poraqueversion}"), (
                "the fallback must come after the input, or it would win")


@pytest.mark.parametrize("guide", GUIDES)
class TestTheMakefileGeneratesTheStamp:
    def test_it_reads_the_package_version(self, guide):
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "src/poraque/version.py" in makefile
        assert "poraque_version.tex" in makefile

    def test_the_pdf_depends_on_the_stamp(self, guide):
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "$(DOC).pdf: $(DOC).tex $(VERSION_STAMP)" in makefile

    def test_latexmk_is_forced(self, guide):
        """
        ``clean`` deletes .fdb_latexmk, so without ``-g`` latexmk compares only
        against the .tex, reports "up-to-date", and leaves a stale version on
        the page even though make invoked it because the version changed.
        """
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "$(LATEXMK) -g $(DOC).tex" in makefile


class TestTheStampMatchesThePackage:
    def test_the_extraction_finds_the_version(self):
        """The sed in the Makefile and the package must agree."""
        import subprocess

        source = os.path.join(ROOT, "src", "poraque", "version.py")
        extracted = subprocess.run(
            ["sed", "-n",
             r"""s/^__version__[[:space:]]*=[[:space:]]*["']\([^"']*\)["'].*/\1/p""",
             source],
            capture_output=True, text=True, check=True).stdout.strip()

        from poraque.version import __version__

        assert extracted == __version__, (
            f"the Makefile would stamp {extracted!r}, the package is "
            f"{__version__!r}")

    @pytest.mark.parametrize("guide", GUIDES)
    def test_a_built_pdf_carries_the_current_version(self, guide):
        """End-to-end, when a build is actually present."""
        import shutil
        import subprocess

        pdf = os.path.join(ROOT, "latex", f"{guide}.pdf")
        if not os.path.exists(pdf):
            pytest.skip("guide not built; run `make -C latex`")
        if not shutil.which("pdftotext"):
            pytest.skip("needs poppler's pdftotext")

        from poraque.version import __version__

        text = subprocess.run(["pdftotext", "-f", "1", "-l", "1", pdf, "-"],
                              capture_output=True, text=True,
                              check=True).stdout
        assert f"Version {__version__}" in text, (
            f"the built PDF does not carry {__version__}; rebuild with "
            f"`make -C latex`")


@pytest.mark.parametrize("guide", GUIDES)
class TestCoverPalette:
    r"""
    Four colours, and the darkest has exactly one permitted use.

    The palette is one sweep of hues -- 48 -> 77 -> 160 -> 163 degrees --
    anchored on the yellow the logo is drawn in. ``poraquecover`` is the
    outlier: it exists only to be the ground a cover is printed on, and at
    1.37:1 against ``poraquegreen`` it buys nothing anywhere else. The name
    states the restriction; these tests enforce it.
    """

    PALETTE = {
        "poraqueyellow": "255,204,0",
        "poraquelime": "163,198,75",
        "poraquegreen": "15,61,46",
        "poraquecover": "6,35,27",
    }

    def test_every_colour_is_defined(self, guide):
        source = _read(f"latex/{guide}.tex")
        for name, rgb in self.PALETTE.items():
            assert f"\\definecolor{{{name}}}{{RGB}}{{{rgb}}}" in source, name

    def test_the_old_red_palette_is_gone(self, guide):
        source = _read(f"latex/{guide}.tex")
        assert "{RGB}{248,65,55}" not in source, "the old brand red survives"

    def test_the_cover_ground_is_used_only_for_the_cover(self, guide):
        source = _read(f"latex/{guide}.tex")
        uses = [line.strip() for line in source.splitlines()
                if "poraquecover" in line and not line.strip().startswith("%")]
        # One \definecolor, and one full-page rule on the title page.
        assert len(uses) == 2, uses
        assert uses[0].startswith(r"\definecolor{poraquecover}")
        assert r"\paperwidth" in uses[1] and r"\paperheight" in uses[1], uses[1]

    def test_the_cover_uses_the_dark_ground_logo(self, guide):
        source = _read(f"latex/{guide}.tex")
        cover = source[source.index(r"\begin{titlepage}"):
                       source.index(r"\end{titlepage}")]
        assert "logo_dark.png" in cover
        assert "logo_light.png" not in cover, (
            "the light logo is for the running header, on white")

    def test_the_yellow_never_carries_text(self, guide):
        """
        Yellow on white is 1.7:1 -- below even the 3:1 large-text floor. It
        carries rules and bands; the green (12.2:1) carries anything read.
        """
        source = _read(f"latex/{guide}.tex")
        for forbidden in ("coltitle=poraqueyellow", "linkcolor=poraqueyellow",
                          "urlcolor=poraqueyellow"):
            assert forbidden not in source, forbidden
