# -*- coding: utf-8 -*-
# file: test_guides.py

"""
The LaTeX guides must not carry a version of their own.

Both did, as literals on the title page, and both had drifted: the user guide
said 26.8.18 and the technical guide 26.6.4 while the package was on 26.8.27.
A version a reader cannot trust is worse than no version, and nothing in a
PDF build fails when it goes stale — so it needs a test.
"""

import os
import re

import pytest

ROOT = os.path.join(os.path.dirname(__file__), "..")
GUIDES = ("user_guide/poraque_user_guide",
          "technical_guide/poraque_technical_guide")


def _read(relative):
    with open(os.path.join(ROOT, relative)) as handle:
        return handle.read()


@pytest.mark.parametrize("guide", GUIDES)
class TestVersionIsNotHardCoded:
    def test_the_title_page_uses_the_macro(self, guide):
        source = _read(f"latex/{guide}.tex")
        assert r"\poraqueversion" in source

    def test_no_literal_version_survives(self, guide):
        """
        A bare ``Version 26.8.18`` on the title page is exactly the failure
        this replaced.
        """
        source = _read(f"latex/{guide}.tex")
        literals = re.findall(r"Version\s+\d+\.\d+\.\d+", source)
        assert not literals, f"hard-coded version(s): {literals}"

    def test_the_macro_has_a_fallback(self, guide):
        """
        The stamp is generated by the Makefile. Compiled directly with
        ``pdflatex``, the document must still build rather than die on an
        undefined control sequence.
        """
        source = _read(f"latex/{guide}.tex")
        assert r"\providecommand{\poraqueversion}" in source
        assert source.index(r"\IfFileExists{poraque_version.tex}") < \
            source.index(r"\providecommand{\poraqueversion}"), (
                "the fallback must come after the input, or it would win")


@pytest.mark.parametrize("guide", GUIDES)
class TestTheMakefileGeneratesTheStamp:
    def test_it_reads_the_package_version(self, guide):
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "src/poraque/version.py" in makefile
        assert "poraque_version.tex" in makefile

    def test_the_pdf_depends_on_the_stamp(self, guide):
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "$(DOC).pdf: $(DOC).tex $(VERSION_STAMP)" in makefile

    def test_latexmk_is_forced(self, guide):
        """
        ``clean`` deletes .fdb_latexmk, so without ``-g`` latexmk compares only
        against the .tex, reports "up-to-date", and leaves a stale version on
        the page even though make invoked it because the version changed.
        """
        makefile = _read(f"latex/{os.path.dirname(guide)}/Makefile")
        assert "$(LATEXMK) -g $(DOC).tex" in makefile


class TestTheStampMatchesThePackage:
    def test_the_extraction_finds_the_version(self):
        """The sed in the Makefile and the package must agree."""
        import subprocess

        source = os.path.join(ROOT, "src", "poraque", "version.py")
        extracted = subprocess.run(
            ["sed", "-n",
             r"""s/^__version__[[:space:]]*=[[:space:]]*["']\([^"']*\)["'].*/\1/p""",
             source],
            capture_output=True, text=True, check=True).stdout.strip()

        from poraque.version import __version__

        assert extracted == __version__, (
            f"the Makefile would stamp {extracted!r}, the package is "
            f"{__version__!r}")

    @pytest.mark.parametrize("guide", GUIDES)
    def test_a_built_pdf_carries_the_current_version(self, guide):
        """End-to-end, when a build is actually present."""
        import shutil
        import subprocess

        pdf = os.path.join(ROOT, "latex", f"{guide}.pdf")
        if not os.path.exists(pdf):
            pytest.skip("guide not built; run `make -C latex`")
        if not shutil.which("pdftotext"):
            pytest.skip("needs poppler's pdftotext")

        from poraque.version import __version__

        text = subprocess.run(["pdftotext", "-f", "1", "-l", "1", pdf, "-"],
                              capture_output=True, text=True,
                              check=True).stdout
        assert f"Version {__version__}" in text, (
            f"the built PDF does not carry {__version__}; rebuild with "
            f"`make -C latex`")
