# -*- coding: utf-8 -*-
# file: templates.py

# This code is part of Poraquê.
# MIT License
#
# Copyright (c) 2026 Leandro Seixas Rocha <leandro.rocha@ilum.cnpem.br>

r"""
The VASP input decks Poraquê asks for, as text rather than as folklore.

Two decks matter to this project, and both had been living in a shell history
rather than in the repository:

**Generating training data** (:func:`tau_incar`). A ``CHGCAR`` comes out of any
run; a ``TAUCAR`` does not. It needs ``LTAU = .TRUE.`` — whose default is
``.FALSE.`` outside meta-GGA — together with ``LCHARG = .TRUE.``, which is what
actually writes both files. The gold dataset was generated instead with a
``TAUCAR = .TRUE.`` line that is not a VASP tag at all, by a patched build, and
every kinetic energy density it produced had to be thrown away. See
``DELETIONS.md``. Having the correct deck in the source tree, next to the gate
that enforces it, is the cheapest possible guard against a repeat.

**Consuming a prediction** (:func:`band_structure_incar`). A predicted density
is only useful to VASP if VASP will read it, and the way to make it read one
without re-converging it is ``ICHARG = 11``: one non-self-consistent
diagonalization at fixed density, which is exactly the band structure a
predicted ``CHGCAR`` is wanted for.

Nothing here runs VASP. These are files to be written next to a structure and
handed to a queue.

.. note::
   The **VASP 6.6.1 minimum** and the ``LTAU`` requirement are *user-specified*
   for this project, not statements about VASP in general: VASP has written
   ``TAUCAR`` for meta-GGA runs far longer than that. 6.6.1 is the version this
   project's τ data will be regenerated with and therefore the only one its
   conventions have been checked against.
"""

import os

#: Minimum VASP release this project accepts kinetic energy density from.
#: User-specified — see the module note.
REQUIRED_VASP_VERSION = "6.6.1"

#: Header stamped on every generated deck, so a file found later in a scratch
#: directory says where it came from without anyone having to guess.
_BANNER = """\
# Generated by Poraque ({purpose}).
# Requires VASP >= {version} (user-specified for this project).
"""


def tau_incar(system="poraque", encut=450, ediff=1e-8, ispin=1, prec="Accurate",
              extra=None):
    r"""
    An ``INCAR`` that writes both ``CHGCAR`` and ``TAUCAR``.

    The three lines that matter are ``LTAU``, ``LCHARG`` and ``LASPH``; the rest
    is an ordinary well-converged static run and can be overridden freely.

    ``LTAU = .TRUE.`` requests evaluation of :math:`\tau(\mathbf r)`;
    ``LCHARG = .TRUE.`` is what writes the density *and* the kinetic energy
    density to disk. Setting the first without the second evaluates τ and
    discards it.

    Parameters
    ----------
    system : str, optional
        ``SYSTEM`` label.
    encut : float, optional
        Plane-wave cutoff in eV.
    ediff : float, optional
        Electronic convergence. Tight by default: τ is a training *label*, and
        a label converged to 1e-4 is noise at the level the operator is being
        asked to reproduce.
    ispin : int, optional
        1 or 2.
    prec : str, optional
        ``PREC``. ``Accurate`` fixes the fine FFT grid the fields are written on.
    extra : dict, optional
        Additional ``{TAG: value}`` lines, appended verbatim. Anything here
        overrides a default of the same name.

    Returns
    -------
    str
        The file contents.

    Examples
    --------
    >>> deck = tau_incar(system="Au supercell", encut=450)
    >>> "LTAU" in deck and ".TRUE." in deck and "LCHARG" in deck
    True
    """
    tags = [
        ("SYSTEM", system),
        ("PREC", prec),
        ("ENCUT", encut),
        ("ISPIN", ispin),
        ("ALGO", "Normal"),
        ("EDIFF", f"{ediff:g}"),
        ("NELM", 500),
        ("NELMIN", 4),
        ("ISMEAR", -1),
        ("SIGMA", 0.05),
        ("NSW", 0),
        ("IBRION", -1),
        ("LASPH", ".TRUE."),
        ("LMAXMIX", 4),
        ("LTAU", ".TRUE."),
        ("LCHARG", ".TRUE."),
        ("LWAVE", ".FALSE."),
    ]
    comments = {
        "LTAU": "evaluate the kinetic energy density (default .FALSE. "
                "outside meta-GGA)",
        "LCHARG": "write CHGCAR *and* TAUCAR; LTAU alone only evaluates tau",
        "LASPH": "aspherical gradient corrections -- on for d/f elements",
        "LMAXMIX": "one-centre occupancies written to CHGCAR up to this l "
                   "(4 for d, 6 for f)",
        "EDIFF": "tau is a training label; converge it like one",
        "PREC": "fixes the fine FFT grid the fields are written on",
    }
    body = _render(tags, comments, extra)
    return _BANNER.format(purpose="CHGCAR + TAUCAR training data",
                          version=REQUIRED_VASP_VERSION) + "\n" + body


def band_structure_incar(system="poraque", encut=450, ispin=1, nbands=None,
                         lorbit=11, prec="Accurate", extra=None):
    r"""
    An ``INCAR`` for one non-self-consistent diagonalization at fixed density.

    ``ICHARG = 11`` reads ``CHGCAR`` and holds it constant through the whole
    electronic minimization, so the eigenvalues come from a single
    diagonalization of the Hamiltonian built from *that* density. This is what
    makes a predicted density directly usable: no SCF cycle runs, and the only
    quantum-mechanical step left is the one being asked for.

    Parameters
    ----------
    system : str, optional
    encut : float, optional
        **Must match the density's own run.** A different cutoff means a
        different FFT grid, and VASP will not read a ``CHGCAR`` whose grid does
        not match the one it wants.
    ispin : int, optional
    nbands : int, optional
        ``NBANDS``. Worth setting generously for a band structure — the default
        gives just enough occupied states.
    lorbit : int, optional
        ``LORBIT``, for the projected weights that make a fat-band plot.
    prec : str, optional
    extra : dict, optional
        Additional tags, appended verbatim and overriding defaults.

    Returns
    -------
    str
    """
    tags = [
        ("SYSTEM", system),
        ("PREC", prec),
        ("ENCUT", encut),
        ("ISPIN", ispin),
        ("ICHARG", 11),
        ("ISTART", 0),
        ("ALGO", "Normal"),
        ("EDIFF", "1E-6"),
        ("NELM", 200),
        ("ISMEAR", 0),
        ("SIGMA", 0.05),
        ("NSW", 0),
        ("IBRION", -1),
        ("LORBIT", lorbit),
        ("LMAXMIX", 4),
        ("LCHARG", ".FALSE."),
        ("LWAVE", ".FALSE."),
    ]
    if nbands:
        tags.insert(4, ("NBANDS", int(nbands)))

    comments = {
        "ICHARG": "read CHGCAR and keep it fixed: one non-self-consistent "
                  "diagonalization",
        "ISTART": "do not read a WAVECAR -- there is none for a predicted "
                  "density",
        "ENCUT": "MUST match the run the density's FFT grid came from",
        "LMAXMIX": "must match the CHGCAR's own one-centre occupancies",
        "LCHARG": "the density is an input here, not an output",
    }
    body = _render(tags, comments, extra)
    return _BANNER.format(purpose="ICHARG = 11 band structure",
                          version=REQUIRED_VASP_VERSION) + "\n" + body


def line_mode_kpoints(path, points_per_segment=40, labels=None,
                      comment="band structure"):
    r"""
    A line-mode ``KPOINTS`` file tracing a path through the Brillouin zone.

    Parameters
    ----------
    path : sequence
        Segments as ``[(start, end), ...]`` where each endpoint is a
        fractional :math:`\mathbf k` triple; or a flat list of points, read as
        a continuous path through all of them.
    points_per_segment : int, optional
        Sampling density along each segment.
    labels : sequence of str, optional
        High-symmetry labels, one per point of a flat ``path``. Written as
        trailing comments, which is where VASP tolerates them.
    comment : str, optional

    Returns
    -------
    str

    Notes
    -----
    Line mode is what a band structure wants; a Monkhorst-Pack mesh is what the
    *density* was converged on and is the wrong thing here. The two are not
    interchangeable, which is why this is a separate function rather than a
    flag.
    """
    segments = _as_segments(path)
    lines = [comment, str(int(points_per_segment)), "Line-mode", "Reciprocal"]

    flat_labels = list(labels) if labels else []
    index = 0
    for start, end in segments:
        for point in (start, end):
            label = ""
            if index < len(flat_labels):
                label = f"  ! {flat_labels[index]}"
            lines.append("  {:.8f}  {:.8f}  {:.8f}{}".format(*point, label))
            index += 1
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_band_structure_deck(directory, chgcar=None, structure=None,
                              kpath=None, labels=None, encut=450,
                              points_per_segment=40, system="poraque",
                              nbands=None, extra=None):
    """
    Write ``INCAR`` and ``KPOINTS`` for an ``ICHARG = 11`` run.

    The ``CHGCAR`` and ``POTCAR`` are not written here: the density is the
    thing being validated and must be supplied by the caller, and a ``POTCAR``
    cannot be redistributed. What this produces is the pair of files that are
    otherwise retyped by hand every time.

    Parameters
    ----------
    directory : str
        Destination; created if absent.
    chgcar : str, optional
        Path to the predicted density, copied in as ``CHGCAR`` when given and
        left to the caller when not.
    structure : Poscar, optional
        Written as ``POSCAR``. When omitted and ``chgcar`` is given, the
        structure is taken from the density's own header — a ``CHGCAR`` carries
        one.
    kpath : sequence, optional
        Brillouin-zone path; see :func:`line_mode_kpoints`. Defaults to the
        FCC path Γ-X-W-K-Γ-L-U-W-L-K, which is the right one for this
        project's gold cells and the wrong one for anything else.
    labels : sequence of str, optional
    encut : float, optional
        Must match the density's run.
    points_per_segment : int, optional
    system : str, optional
    nbands : int, optional
    extra : dict, optional

    Returns
    -------
    dict
        ``{name: path}`` of what was written.
    """
    import shutil

    os.makedirs(directory, exist_ok=True)
    written = {}

    if kpath is None:
        kpath, labels = fcc_band_path()

    incar = os.path.join(directory, "INCAR")
    with open(incar, "w") as handle:
        handle.write(band_structure_incar(system=system, encut=encut,
                                          nbands=nbands, extra=extra))
    written["INCAR"] = incar

    kpoints = os.path.join(directory, "KPOINTS")
    with open(kpoints, "w") as handle:
        handle.write(line_mode_kpoints(kpath, points_per_segment,
                                       labels=labels,
                                       comment=f"{system} band structure"))
    written["KPOINTS"] = kpoints

    if structure is None and chgcar is not None:
        from .volumetric import read_structure_header

        structure = read_structure_header(chgcar)
    if structure is not None:
        poscar = os.path.join(directory, "POSCAR")
        with open(poscar, "w") as handle:
            handle.write(structure.to_string(direct=True))
        written["POSCAR"] = poscar

    if chgcar is not None:
        destination = os.path.join(directory, "CHGCAR")
        if os.path.abspath(chgcar) != os.path.abspath(destination):
            shutil.copyfile(chgcar, destination)
        written["CHGCAR"] = destination

    return written


def fcc_band_path():
    """
    The conventional FCC path Γ-X-W-K-Γ-L-U-W-L-K, with labels.

    Returns
    -------
    tuple
        ``(segments, labels)`` ready for :func:`line_mode_kpoints`.
    """
    points = {
        "G": (0.0, 0.0, 0.0), "X": (0.5, 0.0, 0.5), "W": (0.5, 0.25, 0.75),
        "K": (0.375, 0.375, 0.75), "L": (0.5, 0.5, 0.5),
        "U": (0.625, 0.25, 0.625),
    }
    route = ["G", "X", "W", "K", "G", "L", "U", "W", "L", "K"]
    segments = [(points[a], points[b]) for a, b in zip(route, route[1:])]
    labels = [name for a, b in zip(route, route[1:]) for name in (a, b)]
    return segments, labels


# ---------------------------------------------------------------------- #
# Helpers
# ---------------------------------------------------------------------- #
def _render(tags, comments, extra):
    """Lay out ``TAG = VALUE  # comment`` lines, aligned."""
    values = dict(tags)
    order = [name for name, _ in tags]
    for name, value in (extra or {}).items():
        name = str(name).upper()
        if name not in values:
            order.append(name)
        values[name] = value

    width = max(len(name) for name in order)
    lines = []
    for name in order:
        line = f"{name:<{width}} = {values[name]}"
        note = comments.get(name)
        lines.append(f"{line}  # {note}" if note else line)
    return "\n".join(lines) + "\n"


def _as_segments(path):
    """Accept either explicit segments or a flat continuous path."""
    path = list(path)
    if path and len(path[0]) == 2 and not _is_point(path[0]):
        return [(tuple(start), tuple(end)) for start, end in path]
    points = [tuple(point) for point in path]
    return list(zip(points, points[1:]))


def _is_point(candidate):
    """Whether ``candidate`` is a k-point rather than a pair of them."""
    return all(isinstance(value, (int, float)) for value in candidate)
