task:
  type: all
  name: platinum_model_std 

data:
  potcar_dir: /Users/leseixas/Simulations/vasp/POTCARs

model:
  width: 16
  modes: 8
  projection_channels: 64
  mode_selection: fixed

training:
  physics:
    electron_count_weight: 0.1
    positivity_weight: 0.0
    von_weizsacker_weight: 0.0
    euler_lagrange_weight: 0.0
