task:
  type: all
  name: au_w16_m8_l3

data:
  potcar_dir: /Users/leseixas/Simulations/vasp/POTCARs

model:
  width: 16
  modes: 8
  projection_channels: 64
  mode_selection: fixed

training:
  physics:
    electron_count_weight: 0.1
    positivity_weight: 0.0
    von_weizsacker_weight: 0.0
    euler_lagrange_weight: 0.0

symbolic:
  enable_symbolic_distillation: true
  features: reduced
  template: pauli
  physics:
    enable: true
    positivity_weight: 100.0
    thomas_fermi_weight: 100.0
    von_weizsacker_weight: 100.0
    p_infinity: 1.0e+06
